trigger:
    - main

pool:
    vmImage: 'ubuntu-latest'

jobs:
    - job: Build_Client
      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
                npm install
                npm run build
            displayName: 'Build Client'

          - task: ArchiveFiles@2
            inputs:
                rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
                includeRootFolder: true
                archiveType: 'zip'
                archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                replaceExistingArchive: true
          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

    - deployment: VMDeploy
      dependsOn: Build_Client
      displayName: Deploy
      pool:
          vmImage: 'Ubuntu-18.04'
      environment:
          name: Ubuntu
          resourceType: VirtualMachine
          tags: web
      strategy:
          runOnce:
              deploy:
                  steps:
                      - script: |
                            cd ~/azagent/_work/1/drop
                            rm -rf *
                      - download: current
                        artifact: drop
                      - script: |
                            cd ~/escapebot
                            rm -rf dist
                            cd ~/azagent/_work/1/drop
                            unzip *.zip
                            mv dist ~/escapebot
                            pm2 start dist/index.js --name escapebot_az
